---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: LundOS
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - from-file: sections/default-flatpaks.yml
  - from-file: sections/default-rpms.yml
  - from-file: sections/gnome-extensions.yml
  - from-file: sections/gnome-flatpaks.yml
  - from-file: sections/gnome-rpms.yml
  # - from-file: sections/ghostty.yml
    
  - type: files
    files:
      - source: system
        destination: /

  - type: bling
    install:
      - dconf-update-service

  - type: signing
