modules:
  - type: brew
      
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.dvlv.boxbuddyrs      # BoxBuddy
        - org.fedoraproject.MediaWriter  # Fedora Media Writer
        - com.github.tchx84.Flatseal     # Flatseal
        - io.github.flattool.Warehouse   # Warehouse
    user: {}
      
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-%OS_VERSION%/lihaohong-yazi-fedora-%OS_VERSION%.repo
    install:
      # fonts
      - google-droid-fonts-all
      - google-noto-fonts-all
      - google-noto-emoji-fonts
      - google-noto-color-emoji-fonts
      # icons
      - papirus-icon-theme
      - papirus-icon-theme-dark
      - yaru-icon-theme
      # tools
      - atuin
      - bat
      - eza
      - fd
      - fzf
      - git
      - git-delta
      - imagemagick
      - jq
      - just
      - lm_sensors
      - neovim
      - openssh
      - openssl
      - p7zip
      - poppler
      - resvg
      - ripgrep
      - stow
      - tmux
      - yazi
      - zoxide
    remove:
      - firefox
      - firefox-langpacks

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - NerdFontsSymbolsOnly
      
  - type: signing
