modules:
  - type: brew
      
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.dvlv.boxbuddyrs      # BoxBuddy
        - org.fedoraproject.MediaWriter  # Fedora Media Writer
        - com.github.tchx84.Flatseal     # Flatseal
        - io.github.flattool.Warehouse   # Warehouse
    user: {}
      
  - type: rpm-ostree
    install:
      # fonts
      - google-droid-fonts-all
      - google-noto-fonts-all
      - google-noto-emoji-fonts
      - google-noto-color-emoji-fonts
      # gvfs
      - gvfs-afc
      - gvfs-afp
      - gvfs-archive
      - gvfs-fuse
      - gvfs-goa
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      # icons
      - papirus-icon-theme
      - papirus-icon-theme-dark
      - yaru-icon-theme
      # tools
      - git
      - git-delta
      - lm_sensors
      - stow
    remove:
      - firefox
      - firefox-langpacks

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - NerdFontsSymbolsOnly
      
  - type: signing
