modules:
  - type: brew
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.dvlv.boxbuddyrs      # BoxBuddy
        - org.fedoraproject.MediaWriter  # Fedora Media Writer
        - com.github.tchx84.Flatseal     # Flatseal
        - io.github.flattool.Warehouse   # Warehouse
    user: {}
  - type: rpm-ostree
    install:
      - git
      - git-delta
      - google-droid-fonts-all
      - google-noto-fonts-all
      - google-noto-emoji-fonts
      - google-noto-color-emoji-fonts
      - lm_sensors
      - papirus-icon-theme
      - papirus-icon-theme-dark
      - stow
      - yaru-icon-theme
    remove:
      - firefox
      - firefox-langpacks
  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - NerdFontsSymbolsOnly
  - type: signing
